// web-base/src/App.tsx
/*
 * @Description: 
 * @Author: lingshi
 * @Date: 2023-12-24 15:47:36
 * @LastEditTime: 2024-02-21 11:44:37
 * @LastEditors: lingshi
 */
import * as React from 'react';
import { HashRouter as Router } from "react-router-dom";
import { WorkbenchContext } from './store';
import IndexPage from './pages/index';

export default () => {
  return (
    <WorkbenchContext.Provider
      value={{}}
    >
      <Router>
        <IndexPage />
      </Router>
    </WorkbenchContext.Provider>
  )
}

// packages/web-sub-tech/src/App.vue
<!--
 * @Description: 
 * @Author: lingshi
 * @Date: 2024-02-22 15:43:06
 * @LastEditTime: 2024-02-27 09:52:37
 * @LastEditors: lingshi
-->
<script setup lang="ts">
import { RouterLink, RouterView } from 'vue-router'
</script>

<template>
  <div>123</div>
  <RouterView />
</template>

<style lang="scss" scoped>

</style>
